# Lesson Objective — Ames Housing Dataset Project

In this session, we will simulate a realistic data science workflow using the Ames Housing dataset. The focus is not only on data analysis but also on **project structure, reproducibility, and documentation**, which are essential skills for advanced data science practice in both academic and industry settings.

## 1. Environment Setup

The first step involves configuring a reproducible working environment. This includes setting up Python dependencies, defining package versions, and ensuring that the project can be executed consistently across different machines. Proper environment management is critical for collaboration and long-term project maintenance.

In [1]:
#via pycharm
#https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html

#via vscode + anaconda
#https://code.visualstudio.com/docs/python/environments

## 2. Project Scaffolding

A well-defined project structure is essential for reproducibility, collaboration, and long-term maintainability in data science projects. One widely adopted reference is the Cookiecutter Data Science template, which provides best practices for organizing datasets, code, documentation, and outputs in a consistent and scalable way. While this structure is not mandatory, it serves as a strong starting point for professional and academic projects.

Below is a suggested folder organization for the Ames Housing project:

In [2]:
# ames-project/
# │
# ├── data/
# │   ├── raw/
# │   └── processed/
# │
# ├── notebooks/
# ├── src/
# ├── reports/
# │   └── figures/
# │
# ├── README.md
# ├── requirements.txt
# └── .gitignore

It is important to note that this structure is only a recommendation. The exact organization may vary depending on the project scope, team preferences, or specific research needs. The key principle is to maintain clarity, consistency, and separation of concerns so that anyone interacting with the project can quickly understand its components.

### Folder and File Overview
`data/`

This directory stores all datasets used in the project. It is commonly divided into:
-   `raw/` → original, immutable datasets as obtained from the source. These should never be modified directly.
-   `processed/` → cleaned or transformed datasets ready for analysis or modeling.

Maintaining this separation helps ensure reproducibility and traceability of preprocessing steps.

`notebooks/`
This folder contains Jupyter notebooks used for exploratory data analysis (EDA), prototyping models, visualization, and experimentation. Notebooks are ideal for iterative work but should eventually be complemented by modular code in the src/ folder for production-level workflows.

`src/`
The main source code directory. This is where reusable scripts, preprocessing pipelines, feature engineering code, model training routines, and evaluation functions should live. Keeping code modular here improves maintainability and prevents notebooks from becoming overly complex.

`reports/`
This directory stores generated outputs such as analysis reports, summaries, or presentation materials.
-   `figures/` → dedicated subfolder for plots, charts, and visualizations produced during analysis.

Separating outputs from raw analysis helps organize communication artifacts clearly.

`README.md`
This file provides an overview of the project, including:
-   project objectives
-   dataset description
-   environment setup instructions
-   usage guidelines
-   key findings or notes

A good README significantly improves project usability and reproducibility.

`requirements.txt`

This file lists all Python dependencies required to run the project. It can be generated using:

In [3]:
# pip freeze > requirements.txt

and installed with:

In [4]:
# pip install -r requirements.txt

This ensures that collaborators can recreate the same computational environment.

`.gitignore`
This file specifies which files or directories Git should ignore. Typical entries include:

-   temporary files
-   environment-specific configuration files
-   large raw datasets (when not versioned)
-   system-generated artifacts
Proper use of `.gitignore` keeps the repository clean and manageable.

## 3. Dataset Loading

At this stage, we focus on reading the Ames Housing dataset safely and reproducibly. This includes handling file paths, verifying data integrity, and ensuring that the dataset loads correctly into a pandas DataFrame for further analysis.

In [5]:
#libraries
import pandas as pd
import numpy as np

In [6]:
#descarregar o dataset do Kaggle e colocar na pasta data/raw/
# https://www.kaggle.com/datasets/shashanknecrothapa/ames-housing-dataset?resource=download

In [7]:
#leitura do dataset usando pandas
data_path = '../data/raw/AmesHousing.csv'

df = pd.read_csv(data_path)
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

## 4. Initial Data Exploration

At this stage, we conduct a structured exploratory analysis of the Ames Housing dataset to gain a comprehensive understanding of its structure, content, and potential data quality issues. This step goes beyond simple descriptive statistics — it aims to develop contextual awareness of the variables, assess data reliability, and prepare the dataset for downstream modeling tasks.

A key objective is to systematically inspect all columns in the dataframe, ensuring that no variable is overlooked during the initial profiling phase. This includes identifying data types, understanding variable semantics, detecting inconsistencies, and evaluating missing data patterns.

### Variable Typing and Contextual Understanding

Each column should first be classified according to its statistical and computational type, such as:
-   Numerical (continuous or discrete)
-   Categorical (nominal or ordinal)
-   Datetime or temporal variables
-   Identifier-like variables (e.g., IDs)

Beyond technical typing, students should also investigate the semantic meaning of each variable. For example, a variable like `Alley` in the Ames dataset refers to the type of alley access to a property. Understanding this context is essential because missing values in such variables may reflect the absence of an alley rather than incomplete data.

This contextual interpretation is fundamental for making sound preprocessing decisions.

### Summary Profiling Table

As part of the exploratory process, students should construct a summary table where:
-   each row corresponds to a dataset variable, and
-   each column contains descriptive profiling metrics.

This table serves as a compact diagnostic overview of the dataset.

### Description of Each Summary Column

**Number of Values** (`num of values`)

Represents the total number of non-null observations in the column. This helps verify dataset completeness and identify columns with substantial missing information.

---

**Percentage of Missing Values** (`% of missing values`)

Indicates the proportion of missing data relative to the total dataset size. This metric is critical for assessing data quality and determining whether imputation, exclusion, or domain interpretation is required.

---

**Unique Values** (`Categorical Variables`)

Counts the number of distinct categories present in categorical columns. This helps evaluate cardinality, detect potential encoding challenges, and identify variables that may behave like identifiers rather than true categorical features.

---

**Mean** (`Numerical Variables`)

Provides the arithmetic average for numeric columns. Although simple, this statistic offers a first indication of central tendency and can highlight anomalies when compared with medians or expected domain values.

---

**Python Variable Type** (`python type`)

Refers to the pandas dtype assigned to the column (e.g., int64, float64, object, datetime64). This classification is essential for determining appropriate preprocessing steps and verifying whether the inferred dtype aligns with the variable’s intended meaning.

---

**Count of Float Values** (`float`)

Reports how many entries in the column are explicitly stored as floating-point numbers. This is useful for detecting unintended type mixing or numeric coercion issues.

---

**Count of Integer Values** (`int`)

Measures how many values are stored as integers. Differences between integer counts and total numeric observations may indicate type inconsistencies or missing-value casting effects.

---

**Count of String Values** (`str`)

Indicates the number of string-type observations. This is particularly useful in columns expected to be numeric, where the presence of strings may signal parsing errors, data corruption, or inconsistent data entry.

### Validation and Consistency Check

Students should perform a manual double-check of the generated summary table to ensure correctness. Automated profiling can sometimes produce misleading results due to hidden type coercion, encoding issues, or missing-value representations.

This verification step encourages critical thinking and reinforces an important principle in advanced data science:

> Automated analysis should always be complemented by human validation.

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   str
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   str
 7   Alley            198 non-null    str
 8   Lot Shape        2930 non-null   str
 9   Land Contour     2930 non-null   str
 10  Utilities        2930 non-null   str
 11  Lot Config       2930 non-null   str
 12  Land Slope       2930 non-null   str
 13  Neighborhood     2930 non-null   str
 14  Condition 1      2930 non-null   str
 15  Condition 2      2930 non-null   str
 16  Bldg Type        2930 non-null   str
 17  House Style      2930 non-null   str
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   str
 23  Roof Matl        2930 non-null   str
 24  Exterior 1st     2930 non-null   str
 25  Exterior 2nd     2930 non-null   str
 26  Mas Vnr Type     1155 non-null   str
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   str
 29  Exter Cond       2930 non-null   str
 30  Foundation       2930 non-null   str
 31  Bsmt Qual        2850 non-null   str
 32  Bsmt Cond        2850 non-null   str
 33  Bsmt Exposure    2847 non-null   str
 34  BsmtFin Type 1   2850 non-null   str
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   str
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   str
 41  Heating QC       2930 non-null   str
 42  Central Air      2930 non-null   str
 43  Electrical       2929 non-null   str
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   str
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   str
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   str
 59  Garage Type      2773 non-null   str
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   str
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   str
 65  Garage Cond      2771 non-null   str
 66  Paved Drive      2930 non-null   str
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc Feature     106 non-null    str
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   str
 80  Sale Condition   2930 non-null   str
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 1.8 MB

In [9]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [10]:
categorical_var = df.select_dtypes(include=['object', 'str']).columns.to_list()
numerical_var = df.select_dtypes(include=np.number).columns.to_list()

In [11]:
len(categorical_var)

43

In [12]:
for col in categorical_var:
    print(df[col].value_counts(), "\n")

MS Zoning
RL         2273
RM          462
FV          139
RH           27
C (all)      25
I (all)       2
A (agr)       2
Name: count, dtype: int64

Street
Pave    2918
Grvl      12
Name: count, dtype: int64

Alley
Grvl    120
Pave     78
Name: count, dtype: int64

Lot Shape
Reg    1859
IR1     979
IR2      76
IR3      16
Name: count, dtype: int64

Land Contour
Lvl    2633
HLS     120
Bnk     117
Low      60
Name: count, dtype: int64

Utilities
AllPub    2927
NoSewr       2
NoSeWa       1
Name: count, dtype: int64

Lot Config
Inside     2140
Corner      511
CulDSac     180
FR2          85
FR3          14
Name: count, dtype: int64

Land Slope
Gtl    2789
Mod     125
Sev      16
Name: count, dtype: int64

Neighborhood
NAmes      443
CollgCr    267
OldTown    239
Edwards    194
Somerst    182
NridgHt    166
Gilbert    165
Sawyer     151
NWAmes     131
SawyerW    125
Mitchel    114
BrkSide    108
Crawfor    103
IDOTRR      93
Timber      72
NoRidge     71
StoneBr     51
SWISU       48
ClearCr     44
MeadowV     37
BrDale      30
Blmngtn     28
Veenker     24
NPkVill     23
Blueste     10
Greens       8
GrnHill      2
Landmrk      1
Name: count, dtype: int64

Condition 1
Norm      2522
Feedr      164
Artery      92
RRAn        50
PosN        39
RRAe        28
PosA        20
RRNn         9
RRNe         6
Name: count, dtype: int64

Condition 2
Norm      2900
Feedr       13
Artery       5
PosA         4
PosN         4
RRNn         2
RRAe         1
RRAn         1
Name: count, dtype: int64

Bldg Type
1Fam      2425
TwnhsE     233
Duplex     109
Twnhs      101
2fmCon      62
Name: count, dtype: int64

House Style
1Story    1481
2Story     873
1.5Fin     314
SLvl       128
SFoyer      83
2.5Unf      24
1.5Unf      19
2.5Fin       8
Name: count, dtype: int64

Roof Style
Gable      2321
Hip         551
Gambrel      22
Flat         20
Mansard      11
Shed          5
Name: count, dtype: int64

Roof Matl
CompShg    2887
Tar&Grv      23
WdShake       9
WdShngl       7
Membran       1
ClyTile       1
Roll          1
Metal         1
Name: count, dtype: int64

Exterior 1st
VinylSd    1026
MetalSd     450
HdBoard     442
Wd Sdng     420
Plywood     221
CemntBd     126
BrkFace      88
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
CBlock        2
Stone         2
PreCast       1
ImStucc       1
Name: count, dtype: int64

Exterior 2nd
VinylSd    1015
MetalSd     447
HdBoard     406
Wd Sdng     397
Plywood     274
CmentBd     126
Wd Shng      81
BrkFace      47
Stucco       47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
PreCast       1
Other         1
Name: count, dtype: int64

Mas Vnr Type
BrkFace    880
Stone      249
BrkCmn      25
CBlock       1
Name: count, dtype: int64

Exter Qual
TA    1799
Gd     989
Ex     107
Fa      35
Name: count, dtype: int64

Exter Cond
TA    2549
Gd     299
Fa      67
Ex      12
Po       3
Name: count, dtype: int64

Foundation
PConc     1310
CBlock    1244
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: count, dtype: int64

Bsmt Qual
TA    1283
Gd    1219
Ex     258
Fa      88
Po       2
Name: count, dtype: int64

Bsmt Cond
TA    2616
Gd     122
Fa     104
Po       5
Ex       3
Name: count, dtype: int64

Bsmt Exposure
No    1906
Av     418
Gd     284
Mn     239
Name: count, dtype: int64

BsmtFin Type 1
GLQ    859
Unf    851
ALQ    429
Rec    288
BLQ    269
LwQ    154
Name: count, dtype: int64

BsmtFin Type 2
Unf    2499
Rec     106
LwQ      89
BLQ      68
ALQ      53
GLQ      34
Name: count, dtype: int64

Heating
GasA     2885
GasW       27
Grav        9
Wall        6
OthW        2
Floor       1
Name: count, dtype: int64

Heating QC
Ex    1495
TA     864
Gd     476
Fa      92
Po       3
Name: count, dtype: int64

Central Air
Y    2734
N     196
Name: count, dtype: int64

Electrical
SBrkr    2682
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: count, dtype: int64

Kitchen Qual
TA    1494
Gd    1160
Ex     205
Fa      70
Po       1
Name: count, dtype: int64

Functional
Typ     2728
Min2      70
Min1      65
Mod       35
Maj1      19
Maj2       9
Sev        2
Sal        2
Name: count, dtype: int64

Fireplace Qu
Gd    744
TA    600
Fa     75
Po     46
Ex     43
Name: count, dtype: int64

Garage Type
Attchd     1731
Detchd      782
BuiltIn     186
Basment      36
2Types       23
CarPort      15
Name: count, dtype: int64

Garage Finish
Unf    1231
RFn     812
Fin     728
Name: count, dtype: int64

Garage Qual
TA    2615
Fa     124
Gd      24
Po       5
Ex       3
Name: count, dtype: int64

Garage Cond
TA    2665
Fa      74
Gd      15
Po      14
Ex       3
Name: count, dtype: int64

Paved Drive
Y    2652
N     216
P      62
Name: count, dtype: int64

Pool QC
Ex    4
Gd    4
TA    3
Fa    2
Name: count, dtype: int64

Fence
MnPrv    330
GdPrv    118
GdWo     112
MnWw      12
Name: count, dtype: int64

Misc Feature
Shed    95
Gar2     5
Othr     4
Elev     1
TenC     1
Name: count, dtype: int64

Sale Type
WD       2536
New       239
COD        87
ConLD      26
CWD        12
ConLI       9
ConLw       8
Oth         7
Con         5
VWD         1
Name: count, dtype: int64

Sale Condition
Normal     2413
Partial     245
Abnorml     190
Family       46
Alloca       24
AdjLand      12
Name: count, dtype: int64

In [13]:
import pandas as pd
import numpy as np

def summarize_dataframe(df):
    summary_list = []
    
    for col in df.columns:
        
        num_values = df[col].count()
        missing_pct = (df[col].isnull().sum() / len(df)) * 100
        py_type = df[col].dtype
        
        unique_vals = unique_vals = df[col].nunique() if py_type == 'str' else " "
        mean_val = round(df[col].mean(), 3) if py_type == 'int64' or py_type == 'float64' else " "

        float_count = df[col].apply(lambda x: isinstance(x, float) and not pd.isna(x)).sum()
        int_count = df[col].apply(lambda x: isinstance(x, int) and not isinstance(x, bool)).sum()
        str_count = df[col].apply(lambda x: isinstance(x, str)).sum()

        summary_list.append({
            "Variable": col,
            "Num of values": num_values,
            "% of missing values": f"{missing_pct:.2f}%",
            "Unique Values": unique_vals,
            "Mean": mean_val,
            "Python Type": py_type,
            "Count of Float": float_count,
            "Count of int": int_count,
            "Count of str": str_count
        })

    return pd.DataFrame(summary_list)

summary_df = pd.DataFrame(summarize_dataframe(df))
print(summary_df.to_markdown())

|    | Variable        |   Num of values | % of missing values   | Unique Values   | Mean          | Python Type   |   Count of Float |   Count of int |   Count of str |
|---:|:----------------|----------------:|:----------------------|:----------------|:--------------|:--------------|-----------------:|---------------:|---------------:|
|  0 | Order           |            2930 | 0.00%                 |                 | 1465.5        | int64         |                0 |           2930 |              0 |
|  1 | PID             |            2930 | 0.00%                 |                 | 714464496.989 | int64         |                0 |           2930 |              0 |
|  2 | MS SubClass     |            2930 | 0.00%                 |                 | 57.387        | int64         |                0 |           2930 |              0 |
|  3 | MS Zoning       |            2930 | 0.00%                 | 7               |               | str           |                0 |              0 |           2930 |
|  4 | Lot Frontage    |            2440 | 16.72%                |                 | 69.225        | float64       |             2440 |              0 |              0 |
|  5 | Lot Area        |            2930 | 0.00%                 |                 | 10147.922     | int64         |                0 |           2930 |              0 |
|  6 | Street          |            2930 | 0.00%                 | 2               |               | str           |                0 |              0 |           2930 |
|  7 | Alley           |             198 | 93.24%                | 2               |               | str           |                0 |              0 |            198 |
|  8 | Lot Shape       |            2930 | 0.00%                 | 4               |               | str           |                0 |              0 |           2930 |
|  9 | Land Contour    |            2930 | 0.00%                 | 4               |               | str           |                0 |              0 |           2930 |
| 10 | Utilities       |            2930 | 0.00%                 | 3               |               | str           |                0 |              0 |           2930 |
| 11 | Lot Config      |            2930 | 0.00%                 | 5               |               | str           |                0 |              0 |           2930 |
| 12 | Land Slope      |            2930 | 0.00%                 | 3               |               | str           |                0 |              0 |           2930 |
| 13 | Neighborhood    |            2930 | 0.00%                 | 28              |               | str           |                0 |              0 |           2930 |
| 14 | Condition 1     |            2930 | 0.00%                 | 9               |               | str           |                0 |              0 |           2930 |
| 15 | Condition 2     |            2930 | 0.00%                 | 8               |               | str           |                0 |              0 |           2930 |
| 16 | Bldg Type       |            2930 | 0.00%                 | 5               |               | str           |                0 |              0 |           2930 |
| 17 | House Style     |            2930 | 0.00%                 | 8               |               | str           |                0 |              0 |           2930 |
| 18 | Overall Qual    |            2930 | 0.00%                 |                 | 6.095         | int64         |                0 |           2930 |              0 |
| 19 | Overall Cond    |            2930 | 0.00%                 |                 | 5.563         | int64         |                0 |           2930 |              0 |
| 20 | Year Built      |            2930 | 0.00%                 |                 | 1971.356      | int64         |                0 |           2930 |              0 |
| 21 | Year Remod/Add  |            2930 | 0.00%                 |                 | 1984.267      | int64         |                0 |           2930 |              0 |
| 22 | Roof Style      |            2930 | 0.00%                 | 6               |               | str           |                0 |              0 |           2930 |
| 23 | Roof Matl       |            2930 | 0.00%                 | 8               |               | str           |                0 |              0 |           2930 |
| 24 | Exterior 1st    |            2930 | 0.00%                 | 16              |               | str           |                0 |              0 |           2930 |
| 25 | Exterior 2nd    |            2930 | 0.00%                 | 17              |               | str           |                0 |              0 |           2930 |
| 26 | Mas Vnr Type    |            1155 | 60.58%                | 4               |               | str           |                0 |              0 |           1155 |
| 27 | Mas Vnr Area    |            2907 | 0.78%                 |                 | 101.897       | float64       |             2907 |              0 |              0 |
| 28 | Exter Qual      |            2930 | 0.00%                 | 4               |               | str           |                0 |              0 |           2930 |
| 29 | Exter Cond      |            2930 | 0.00%                 | 5               |               | str           |                0 |              0 |           2930 |
| 30 | Foundation      |            2930 | 0.00%                 | 6               |               | str           |                0 |              0 |           2930 |
| 31 | Bsmt Qual       |            2850 | 2.73%                 | 5               |               | str           |                0 |              0 |           2850 |
| 32 | Bsmt Cond       |            2850 | 2.73%                 | 5               |               | str           |                0 |              0 |           2850 |
| 33 | Bsmt Exposure   |            2847 | 2.83%                 | 4               |               | str           |                0 |              0 |           2847 |
| 34 | BsmtFin Type 1  |            2850 | 2.73%                 | 6               |               | str           |                0 |              0 |           2850 |
| 35 | BsmtFin SF 1    |            2929 | 0.03%                 |                 | 442.63        | float64       |             2929 |              0 |              0 |
| 36 | BsmtFin Type 2  |            2849 | 2.76%                 | 6               |               | str           |                0 |              0 |           2849 |
| 37 | BsmtFin SF 2    |            2929 | 0.03%                 |                 | 49.722        | float64       |             2929 |              0 |              0 |
| 38 | Bsmt Unf SF     |            2929 | 0.03%                 |                 | 559.263       | float64       |             2929 |              0 |              0 |
| 39 | Total Bsmt SF   |            2929 | 0.03%                 |                 | 1051.615      | float64       |             2929 |              0 |              0 |
| 40 | Heating         |            2930 | 0.00%                 | 6               |               | str           |                0 |              0 |           2930 |
| 41 | Heating QC      |            2930 | 0.00%                 | 5               |               | str           |                0 |              0 |           2930 |
| 42 | Central Air     |            2930 | 0.00%                 | 2               |               | str           |                0 |              0 |           2930 |
| 43 | Electrical      |            2929 | 0.03%                 | 5               |               | str           |                0 |              0 |           2929 |
| 44 | 1st Flr SF      |            2930 | 0.00%                 |                 | 1159.558      | int64         |                0 |           2930 |              0 |
| 45 | 2nd Flr SF      |            2930 | 0.00%                 |                 | 335.456       | int64         |                0 |           2930 |              0 |
| 46 | Low Qual Fin SF |            2930 | 0.00%                 |                 | 4.677         | int64         |                0 |           2930 |              0 |
| 47 | Gr Liv Area     |            2930 | 0.00%                 |                 | 1499.69       | int64         |                0 |           2930 |              0 |
| 48 | Bsmt Full Bath  |            2928 | 0.07%                 |                 | 0.431         | float64       |             2928 |              0 |              0 |
| 49 | Bsmt Half Bath  |            2928 | 0.07%                 |                 | 0.061         | float64       |             2928 |              0 |              0 |
| 50 | Full Bath       |            2930 | 0.00%                 |                 | 1.567         | int64         |                0 |           2930 |              0 |
| 51 | Half Bath       |            2930 | 0.00%                 |                 | 0.38          | int64         |                0 |           2930 |              0 |
| 52 | Bedroom AbvGr   |            2930 | 0.00%                 |                 | 2.854         | int64         |                0 |           2930 |              0 |
| 53 | Kitchen AbvGr   |            2930 | 0.00%                 |                 | 1.044         | int64         |                0 |           2930 |              0 |
| 54 | Kitchen Qual    |            2930 | 0.00%                 | 5               |               | str           |                0 |              0 |           2930 |
| 55 | TotRms AbvGrd   |            2930 | 0.00%                 |                 | 6.443         | int64         |                0 |           2930 |              0 |
| 56 | Functional      |            2930 | 0.00%                 | 8               |               | str           |                0 |              0 |           2930 |
| 57 | Fireplaces      |            2930 | 0.00%                 |                 | 0.599         | int64         |                0 |           2930 |              0 |
| 58 | Fireplace Qu    |            1508 | 48.53%                | 5               |               | str           |                0 |              0 |           1508 |
| 59 | Garage Type     |            2773 | 5.36%                 | 6               |               | str           |                0 |              0 |           2773 |
| 60 | Garage Yr Blt   |            2771 | 5.43%                 |                 | 1978.132      | float64       |             2771 |              0 |              0 |
| 61 | Garage Finish   |            2771 | 5.43%                 | 3               |               | str           |                0 |              0 |           2771 |
| 62 | Garage Cars     |            2929 | 0.03%                 |                 | 1.767         | float64       |             2929 |              0 |              0 |
| 63 | Garage Area     |            2929 | 0.03%                 |                 | 472.82        | float64       |             2929 |              0 |              0 |
| 64 | Garage Qual     |            2771 | 5.43%                 | 5               |               | str           |                0 |              0 |           2771 |
| 65 | Garage Cond     |            2771 | 5.43%                 | 5               |               | str           |                0 |              0 |           2771 |
| 66 | Paved Drive     |            2930 | 0.00%                 | 3               |               | str           |                0 |              0 |           2930 |
| 67 | Wood Deck SF    |            2930 | 0.00%                 |                 | 93.752        | int64         |                0 |           2930 |              0 |
| 68 | Open Porch SF   |            2930 | 0.00%                 |                 | 47.533        | int64         |                0 |           2930 |              0 |
| 69 | Enclosed Porch  |            2930 | 0.00%                 |                 | 23.012        | int64         |                0 |           2930 |              0 |
| 70 | 3Ssn Porch      |            2930 | 0.00%                 |                 | 2.592         | int64         |                0 |           2930 |              0 |
| 71 | Screen Porch    |            2930 | 0.00%                 |                 | 16.002        | int64         |                0 |           2930 |              0 |
| 72 | Pool Area       |            2930 | 0.00%                 |                 | 2.243         | int64         |                0 |           2930 |              0 |
| 73 | Pool QC         |              13 | 99.56%                | 4               |               | str           |                0 |              0 |             13 |
| 74 | Fence           |             572 | 80.48%                | 4               |               | str           |                0 |              0 |            572 |
| 75 | Misc Feature    |             106 | 96.38%                | 5               |               | str           |                0 |              0 |            106 |
| 76 | Misc Val        |            2930 | 0.00%                 |                 | 50.635        | int64         |                0 |           2930 |              0 |
| 77 | Mo Sold         |            2930 | 0.00%                 |                 | 6.216         | int64         |                0 |           2930 |              0 |
| 78 | Yr Sold         |            2930 | 0.00%                 |                 | 2007.79       | int64         |                0 |           2930 |              0 |
| 79 | Sale Type       |            2930 | 0.00%                 | 10              |               | str           |                0 |              0 |           2930 |
| 80 | Sale Condition  |            2930 | 0.00%                 | 6               |               | str           |                0 |              0 |           2930 |
| 81 | SalePrice       |            2930 | 0.00%                 |                 | 180796.06     | int64         |                0 |           2930 |              0 |

In [14]:
summary_df.to_markdown("../reports/SummaryProfilingTable.md", index=False)

In [15]:
df[['Alley']].value_counts()

Alley
Grvl     120
Pave      78
Name: count, dtype: int64

In [16]:
df[['Mas Vnr Type']].value_counts()

Mas Vnr Type
BrkFace         880
Stone           249
BrkCmn           25
CBlock            1
Name: count, dtype: int64

In [17]:
df[['Misc Feature']].value_counts()

Misc Feature
Shed            95
Gar2             5
Othr             4
Elev             1
TenC             1
Name: count, dtype: int64

In [18]:
df['Pool QC'].value_counts()

Pool QC
Ex    4
Gd    4
TA    3
Fa    2
Name: count, dtype: int64

In [21]:
df['Alley'].value_counts()

Alley
Grvl    120
Pave     78
Name: count, dtype: int64

## 5. Writing the Project README

The final step of this exercise is to produce a well-structured README file that documents the project clearly and professionally. Writing good documentation is a core skill in advanced data science because it ensures reproducibility, facilitates collaboration, and allows others to quickly understand the purpose, structure, and findings of the project.
The README should be written with the assumption that the reader has no prior knowledge of the project.

### Project Title

Start with a clear and concise project title. The title should reflect the dataset, the analytical focus, or the main objective of the project. A good title immediately communicates the scope and theme of the work.

### Project Description

(Background, Motivation, and Objectives)

Provide a short but informative overview of the project. This section should include:
-   the background context of the problem or dataset
-   the motivation for conducting the analysis
-   the main objectives or research questions

The goal is to help readers understand why the project exists, what problem it addresses, and what outcomes are expected.

### Installation Instructions

Include step-by-step guidance on how to reproduce the working environment. This typically involves:
-   creating and activating a virtual environment
-   installing dependencies (e.g., via requirements.txt)
-   instructions for running notebooks, scripts, or pipelines

Clear installation instructions are essential for reproducibility and collaboration, particularly in academic and professional settings.

### Data Source and Data Structure

Describe the origin of the dataset and how it is organized. This section should include:
-   where the data was obtained (e.g., repository, competition, public dataset)
-   format of the data (CSV, database export, etc.)
-   number of observations and variables
-   general description of key features

This contextual information helps readers interpret the dataset correctly and understand its potential limitations.

### Initial Data Inspection

Provide an overview of the first exploratory analysis. This should include:
-   summary statistics for numerical variables
-   data type classification
-   missing value analysis
-   any notable patterns or irregularities

You may also include visualizations (e.g., distributions, missing-value plots) to support the description. The objective is to demonstrate familiarity with the dataset before deeper analysis.

### Summary Table of Key Variables

Include a summary table containing the most relevant variables identified during the initial exploration. The table should have:
-   a clear caption explaining its purpose
-   well-defined metrics (e.g., missing values, central tendency, type consistency)
-   appropriate formatting for readability

This table serves as a compact diagnostic overview of the dataset.

### Interpretation and Preliminary Insights

Accompany the summary table with a short analytical discussion. This section should:
-   highlight important patterns or anomalies
-   identify possible data quality issues
-   discuss variable relevance for future modeling
-   suggest potential preprocessing steps

This interpretation demonstrates analytical maturity and connects descriptive statistics with the broader data science workflow.

Overall, the README should communicate the project in a structured, professional, and reproducible way. Beyond documenting technical steps, it should reflect critical thinking about the dataset, methodological choices, and next analytical directions.